### ISSUE TITLE
Link or file of dataset is missing

### ISSUE THREAD

**Issue by Anacoder1** [PacktPublishing/Python-Deep-Learning-Cookbook#5]
I was checking out the code of the notebook - "Chapter 4 - Character-level text generation.ipynb" (check this [https://github.com/PacktPublishing/Python-Deep-Learning-Cookbook/blob/master/Chapter04/Chapter%204%20-%20Character-level%20text%20generation.ipynb](link).

I could not find any link to the 'obama.txt' dataset used in the notebook, or any file for the same.

Could anybody provide the same?

**Comment by suwarnarajput** [comment]
Hello team,


I have sent this query to the author. Waiting for author reply.


Thanks and regards,

Suwarna

________________________________

**Comment by suwarnarajput** [comment]
Hello team,


The reader can use these links:

 http://www.librarian.net/dnc/speeches/obama.txt
https://raw.githubusercontent.com/q-n-t-m/obamas-speeches/master/all_obama_speeches.txt


Thanks and regards.

Suwarna

________________________________
